"""Add news and sentiment analysis models

Revision ID: 146761b7effb
Revises: 827bb7d50fb0
Create Date: 2025-09-28 11:07:56.762715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '146761b7effb'
down_revision: Union[str, Sequence[str], None] = '827bb7d50fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('idx_news_articles_is_processed', 'news_articles', ['is_processed'], unique=False)
    op.create_index('idx_news_articles_published_at', 'news_articles', ['published_at'], unique=False)
    op.create_index('idx_news_articles_source_published', 'news_articles', ['source', 'published_at'], unique=False)
    op.create_index('idx_news_articles_url', 'news_articles', ['url'], unique=False)
    op.create_index(op.f('ix_news_articles_id'), 'news_articles', ['id'], unique=False)
    op.create_table('asset_daily_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('avg_sentiment', sa.Float(), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=True),
    sa.Column('sentiment_7d_avg', sa.Float(), nullable=True),
    sa.Column('sentiment_30d_avg', sa.Float(), nullable=True),
    sa.Column('volatility_30d', sa.Float(), nullable=True),
    sa.Column('return_30d', sa.Float(), nullable=True),
    sa.Column('return_365d', sa.Float(), nullable=True),
    sa.Column('fundamental_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_asset_daily_signals_asset', 'asset_daily_signals', ['asset_id'], unique=False)
    op.create_index('idx_asset_daily_signals_asset_date', 'asset_daily_signals', ['asset_id', 'date'], unique=True)
    op.create_index('idx_asset_daily_signals_avg_sentiment', 'asset_daily_signals', ['avg_sentiment'], unique=False)
    op.create_index('idx_asset_daily_signals_date', 'asset_daily_signals', ['date'], unique=False)
    op.create_index(op.f('ix_asset_daily_signals_id'), 'asset_daily_signals', ['id'], unique=False)
    op.create_table('news_asset_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('match_method', sa.String(length=50), nullable=True),
    sa.Column('matched_text', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_news_asset_map_article', 'news_asset_map', ['article_id'], unique=False)
    op.create_index('idx_news_asset_map_article_asset', 'news_asset_map', ['article_id', 'asset_id'], unique=False)
    op.create_index('idx_news_asset_map_asset', 'news_asset_map', ['asset_id'], unique=False)
    op.create_index('idx_news_asset_map_score', 'news_asset_map', ['match_score'], unique=False)
    op.create_index(op.f('ix_news_asset_map_id'), 'news_asset_map', ['id'], unique=False)
    op.create_table('news_sentiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('polarity', sa.Float(), nullable=False),
    sa.Column('pos', sa.Float(), nullable=False),
    sa.Column('neg', sa.Float(), nullable=False),
    sa.Column('neu', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_news_sentiments_article', 'news_sentiments', ['article_id'], unique=False)
    op.create_index('idx_news_sentiments_article_asset', 'news_sentiments', ['article_id', 'asset_id'], unique=False)
    op.create_index('idx_news_sentiments_asset', 'news_sentiments', ['asset_id'], unique=False)
    op.create_index('idx_news_sentiments_asset_created', 'news_sentiments', ['asset_id', 'created_at'], unique=False)
    op.create_index('idx_news_sentiments_created_at', 'news_sentiments', ['created_at'], unique=False)
    op.create_index('idx_news_sentiments_polarity', 'news_sentiments', ['polarity'], unique=False)
    op.create_index(op.f('ix_news_sentiments_id'), 'news_sentiments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_sentiments_id'), table_name='news_sentiments')
    op.drop_index('idx_news_sentiments_polarity', table_name='news_sentiments')
    op.drop_index('idx_news_sentiments_created_at', table_name='news_sentiments')
    op.drop_index('idx_news_sentiments_asset_created', table_name='news_sentiments')
    op.drop_index('idx_news_sentiments_asset', table_name='news_sentiments')
    op.drop_index('idx_news_sentiments_article_asset', table_name='news_sentiments')
    op.drop_index('idx_news_sentiments_article', table_name='news_sentiments')
    op.drop_table('news_sentiments')
    op.drop_index(op.f('ix_news_asset_map_id'), table_name='news_asset_map')
    op.drop_index('idx_news_asset_map_score', table_name='news_asset_map')
    op.drop_index('idx_news_asset_map_asset', table_name='news_asset_map')
    op.drop_index('idx_news_asset_map_article_asset', table_name='news_asset_map')
    op.drop_index('idx_news_asset_map_article', table_name='news_asset_map')
    op.drop_table('news_asset_map')
    op.drop_index(op.f('ix_asset_daily_signals_id'), table_name='asset_daily_signals')
    op.drop_index('idx_asset_daily_signals_date', table_name='asset_daily_signals')
    op.drop_index('idx_asset_daily_signals_avg_sentiment', table_name='asset_daily_signals')
    op.drop_index('idx_asset_daily_signals_asset_date', table_name='asset_daily_signals')
    op.drop_index('idx_asset_daily_signals_asset', table_name='asset_daily_signals')
    op.drop_table('asset_daily_signals')
    op.drop_index(op.f('ix_news_articles_id'), table_name='news_articles')
    op.drop_index('idx_news_articles_url', table_name='news_articles')
    op.drop_index('idx_news_articles_source_published', table_name='news_articles')
    op.drop_index('idx_news_articles_published_at', table_name='news_articles')
    op.drop_index('idx_news_articles_is_processed', table_name='news_articles')
    op.drop_table('news_articles')
    # ### end Alembic commands ###
