"""Add collector_runs table

Revision ID: 4328628ede68
Revises: bf621d40e4e1
Create Date: 2025-10-05 17:11:57.206337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4328628ede68'
down_revision = 'bf621d40e4e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collector_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collector_name', sa.String(length=100), nullable=False),
    sa.Column('run_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_added', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('config_used', sa.JSON(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=True),
    sa.Column('depends_on', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('memory_usage_mb', sa.Float(), nullable=True),
    sa.Column('cpu_time_seconds', sa.Float(), nullable=True),
    sa.Column('api_calls_made', sa.Integer(), nullable=True),
    sa.Column('rate_limit_hits', sa.Integer(), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('is_incremental', sa.Boolean(), nullable=True),
    sa.Column('force_full_refresh', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_index(op.f('ix_collector_runs_collector_name'), 'collector_runs', ['collector_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collector_runs_collector_name'), table_name='collector_runs')
    op.drop_table('collector_runs')
    # ### end Alembic commands ###
