"""Add collector_runs table for orchestrator tracking

Revision ID: 703ff6e6f939
Revises: 00c7eb434f9a
Create Date: 2025-10-03 15:46:19.181872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '703ff6e6f939'
down_revision: Union[str, Sequence[str], None] = '00c7eb434f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
