"""message

Revision ID: 91c95f0866ba
Revises: 
Create Date: 2025-10-04 01:13:24.837181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91c95f0866ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('subtype', sa.String(length=100), nullable=True),
    sa.Column('exchange', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('total_assets', sa.BigInteger(), nullable=True),
    sa.Column('expense_ratio', sa.Float(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('listing_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('delisting_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('cusip', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('idx_news_articles_is_processed', 'news_articles', ['is_processed'], unique=False)
    op.create_index('idx_news_articles_published_at', 'news_articles', ['published_at'], unique=False)
    op.create_index('idx_news_articles_source_published', 'news_articles', ['source', 'published_at'], unique=False)
    op.create_index('idx_news_articles_url', 'news_articles', ['url'], unique=False)
    op.create_index(op.f('ix_news_articles_id'), 'news_articles', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('asset_daily_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('avg_sentiment', sa.Float(), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=True),
    sa.Column('sentiment_7d_avg', sa.Float(), nullable=True),
    sa.Column('sentiment_30d_avg', sa.Float(), nullable=True),
    sa.Column('volatility_30d', sa.Float(), nullable=True),
    sa.Column('return_30d', sa.Float(), nullable=True),
    sa.Column('return_365d', sa.Float(), nullable=True),
    sa.Column('fundamental_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_asset_daily_signals_asset', 'asset_daily_signals', ['asset_id'], unique=False)
    op.create_index('idx_asset_daily_signals_asset_date', 'asset_daily_signals', ['asset_id', 'date'], unique=True)
    op.create_index('idx_asset_daily_signals_avg_sentiment', 'asset_daily_signals', ['avg_sentiment'], unique=False)
    op.create_index('idx_asset_daily_signals_date', 'asset_daily_signals', ['date'], unique=False)
    op.create_index(op.f('ix_asset_daily_signals_id'), 'asset_daily_signals', ['id'], unique=False)
    op.create_table('cryptos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('circulating_supply', sa.BigInteger(), nullable=True),
    sa.Column('total_supply', sa.BigInteger(), nullable=True),
    sa.Column('max_supply', sa.BigInteger(), nullable=True),
    sa.Column('algorithm', sa.String(length=100), nullable=True),
    sa.Column('consensus_mechanism', sa.String(length=50), nullable=True),
    sa.Column('blockchain', sa.String(length=100), nullable=True),
    sa.Column('token_type', sa.String(length=50), nullable=True),
    sa.Column('contract_address', sa.String(length=100), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=True),
    sa.Column('all_time_high', sa.Float(), nullable=True),
    sa.Column('all_time_high_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('all_time_low', sa.Float(), nullable=True),
    sa.Column('all_time_low_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('block_time', sa.Float(), nullable=True),
    sa.Column('hashing_algorithm', sa.String(length=100), nullable=True),
    sa.Column('launch_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('whitepaper_url', sa.String(length=500), nullable=True),
    sa.Column('source_code_url', sa.String(length=500), nullable=True),
    sa.Column('reddit_subscribers', sa.Integer(), nullable=True),
    sa.Column('twitter_followers', sa.Integer(), nullable=True),
    sa.Column('telegram_members', sa.Integer(), nullable=True),
    sa.Column('is_minable', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    op.create_index(op.f('ix_cryptos_id'), 'cryptos', ['id'], unique=False)
    op.create_table('daily_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('high_price', sa.Float(), nullable=True),
    sa.Column('low_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('dividends', sa.Float(), nullable=True),
    sa.Column('stock_splits', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'date', name='uix_asset_date')
    )
    op.create_index(op.f('ix_daily_prices_id'), 'daily_prices', ['id'], unique=False)
    op.create_table('etfs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('nav', sa.Float(), nullable=True),
    sa.Column('expense_ratio', sa.Float(), nullable=True),
    sa.Column('underlying_index', sa.String(length=255), nullable=True),
    sa.Column('index_provider', sa.String(length=100), nullable=True),
    sa.Column('top_10_holdings_weight', sa.Float(), nullable=True),
    sa.Column('number_of_holdings', sa.Integer(), nullable=True),
    sa.Column('tracking_error', sa.Float(), nullable=True),
    sa.Column('avg_daily_volume', sa.Integer(), nullable=True),
    sa.Column('inception_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('fund_manager', sa.String(length=255), nullable=True),
    sa.Column('benchmark', sa.String(length=255), nullable=True),
    sa.Column('investment_objective', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    op.create_index(op.f('ix_etfs_id'), 'etfs', ['id'], unique=False)
    op.create_table('mutual_funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('nav', sa.Float(), nullable=True),
    sa.Column('expense_ratio', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('fund_manager', sa.String(length=255), nullable=True),
    sa.Column('amc_name', sa.String(length=255), nullable=True),
    sa.Column('minimum_investment', sa.BigInteger(), nullable=True),
    sa.Column('minimum_sip', sa.Integer(), nullable=True),
    sa.Column('exit_load', sa.Float(), nullable=True),
    sa.Column('aum', sa.BigInteger(), nullable=True),
    sa.Column('alpha', sa.Float(), nullable=True),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('standard_deviation', sa.Float(), nullable=True),
    sa.Column('return_1yr', sa.Float(), nullable=True),
    sa.Column('return_3yr', sa.Float(), nullable=True),
    sa.Column('return_5yr', sa.Float(), nullable=True),
    sa.Column('return_since_inception', sa.Float(), nullable=True),
    sa.Column('inception_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('benchmark', sa.String(length=255), nullable=True),
    sa.Column('investment_objective', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    op.create_index(op.f('ix_mutual_funds_id'), 'mutual_funds', ['id'], unique=False)
    op.create_table('news_asset_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('match_method', sa.String(length=50), nullable=True),
    sa.Column('matched_text', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_news_asset_map_article', 'news_asset_map', ['article_id'], unique=False)
    op.create_index('idx_news_asset_map_article_asset', 'news_asset_map', ['article_id', 'asset_id'], unique=False)
    op.create_index('idx_news_asset_map_asset', 'news_asset_map', ['asset_id'], unique=False)
    op.create_index('idx_news_asset_map_score', 'news_asset_map', ['match_score'], unique=False)
    op.create_index(op.f('ix_news_asset_map_id'), 'news_asset_map', ['id'], unique=False)
    op.create_table('news_sentiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('polarity', sa.Float(), nullable=False),
    sa.Column('pos', sa.Float(), nullable=False),
    sa.Column('neg', sa.Float(), nullable=False),
    sa.Column('neu', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_news_sentiments_article', 'news_sentiments', ['article_id'], unique=False)
    op.create_index('idx_news_sentiments_article_asset', 'news_sentiments', ['article_id', 'asset_id'], unique=False)
    op.create_index('idx_news_sentiments_asset', 'news_sentiments', ['asset_id'], unique=False)
    op.create_index('idx_news_sentiments_asset_created', 'news_sentiments', ['asset_id', 'created_at'], unique=False)
    op.create_index('idx_news_sentiments_created_at', 'news_sentiments', ['created_at'], unique=False)
    op.create_index('idx_news_sentiments_polarity', 'news_sentiments', ['polarity'], unique=False)
    op.create_index(op.f('ix_news_sentiments_id'), 'news_sentiments', ['id'], unique=False)
    op.create_table('quarterly_fundamentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('earnings_per_share', sa.Float(), nullable=True),
    sa.Column('price_to_earnings_ratio', sa.Float(), nullable=True),
    sa.Column('total_revenue', sa.BigInteger(), nullable=True),
    sa.Column('net_income', sa.BigInteger(), nullable=True),
    sa.Column('total_debt', sa.BigInteger(), nullable=True),
    sa.Column('return_on_equity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'report_date', name='uix_asset_report')
    )
    op.create_index(op.f('ix_quarterly_fundamentals_id'), 'quarterly_fundamentals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quarterly_fundamentals_id'), table_name='quarterly_fundamentals')
    op.drop_table('quarterly_fundamentals')
    op.drop_index(op.f('ix_news_sentiments_id'), table_name='news_sentiments')
    op.drop_index('idx_news_sentiments_polarity', table_name='news_sentiments')
    op.drop_index('idx_news_sentiments_created_at', table_name='news_sentiments')
    op.drop_index('idx_news_sentiments_asset_created', table_name='news_sentiments')
    op.drop_index('idx_news_sentiments_asset', table_name='news_sentiments')
    op.drop_index('idx_news_sentiments_article_asset', table_name='news_sentiments')
    op.drop_index('idx_news_sentiments_article', table_name='news_sentiments')
    op.drop_table('news_sentiments')
    op.drop_index(op.f('ix_news_asset_map_id'), table_name='news_asset_map')
    op.drop_index('idx_news_asset_map_score', table_name='news_asset_map')
    op.drop_index('idx_news_asset_map_asset', table_name='news_asset_map')
    op.drop_index('idx_news_asset_map_article_asset', table_name='news_asset_map')
    op.drop_index('idx_news_asset_map_article', table_name='news_asset_map')
    op.drop_table('news_asset_map')
    op.drop_index(op.f('ix_mutual_funds_id'), table_name='mutual_funds')
    op.drop_table('mutual_funds')
    op.drop_index(op.f('ix_etfs_id'), table_name='etfs')
    op.drop_table('etfs')
    op.drop_index(op.f('ix_daily_prices_id'), table_name='daily_prices')
    op.drop_table('daily_prices')
    op.drop_index(op.f('ix_cryptos_id'), table_name='cryptos')
    op.drop_table('cryptos')
    op.drop_index(op.f('ix_asset_daily_signals_id'), table_name='asset_daily_signals')
    op.drop_index('idx_asset_daily_signals_date', table_name='asset_daily_signals')
    op.drop_index('idx_asset_daily_signals_avg_sentiment', table_name='asset_daily_signals')
    op.drop_index('idx_asset_daily_signals_asset_date', table_name='asset_daily_signals')
    op.drop_index('idx_asset_daily_signals_asset', table_name='asset_daily_signals')
    op.drop_table('asset_daily_signals')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_news_articles_id'), table_name='news_articles')
    op.drop_index('idx_news_articles_url', table_name='news_articles')
    op.drop_index('idx_news_articles_source_published', table_name='news_articles')
    op.drop_index('idx_news_articles_published_at', table_name='news_articles')
    op.drop_index('idx_news_articles_is_processed', table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
