"""change_bigint_to_numeric

Revision ID: acfecb36e410
Revises: b549e33bbbac
Create Date: 2025-10-06 02:42:27.217982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acfecb36e410'
down_revision = 'b549e33bbbac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
