"""change_bigint_to_numeric_for_large_values

Revision ID: b549e33bbbac
Revises: 531e271e966d
Create Date: 2025-10-06 01:51:00.800620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b549e33bbbac'
down_revision = '531e271e966d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quarterly_fundamentals', 'total_revenue',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'cost_of_revenue',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'gross_profit',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'operating_income',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'net_income',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'ebitda',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'total_assets',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'total_liabilities',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'total_equity',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'total_debt',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'cash_and_equivalents',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'operating_cash_flow',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'free_cash_flow',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'capital_expenditure',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'shares_outstanding',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'market_cap',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'enterprise_value',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quarterly_fundamentals', 'enterprise_value',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'market_cap',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'shares_outstanding',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'capital_expenditure',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'free_cash_flow',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'operating_cash_flow',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'cash_and_equivalents',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'total_debt',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'total_equity',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'total_liabilities',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'total_assets',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'ebitda',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'net_income',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'operating_income',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'gross_profit',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'cost_of_revenue',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('quarterly_fundamentals', 'total_revenue',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
