"""add_asset_link_and_sentiment_to_news

Revision ID: cde6ba75700e
Revises: 05555c5b9cbe
Create Date: 2025-10-08 00:31:20.719128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cde6ba75700e'
down_revision = '05555c5b9cbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_articles', sa.Column('asset_id', sa.Integer(), nullable=True))
    op.add_column('news_articles', sa.Column('asset_symbol', sa.String(length=50), nullable=True))
    op.add_column('news_articles', sa.Column('sentiment_score', sa.Float(), nullable=True))
    op.add_column('news_articles', sa.Column('sentiment_label', sa.String(length=20), nullable=True))
    op.create_index('idx_news_articles_asset_id', 'news_articles', ['asset_id'], unique=False)
    op.create_index('idx_news_articles_asset_published', 'news_articles', ['asset_id', 'published_at'], unique=False)
    op.create_index('idx_news_articles_asset_symbol', 'news_articles', ['asset_symbol'], unique=False)
    op.create_index(op.f('ix_news_articles_asset_id'), 'news_articles', ['asset_id'], unique=False)
    op.create_index(op.f('ix_news_articles_asset_symbol'), 'news_articles', ['asset_symbol'], unique=False)
    op.create_foreign_key(None, 'news_articles', 'assets', ['asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news_articles', type_='foreignkey')
    op.drop_index(op.f('ix_news_articles_asset_symbol'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_asset_id'), table_name='news_articles')
    op.drop_index('idx_news_articles_asset_symbol', table_name='news_articles')
    op.drop_index('idx_news_articles_asset_published', table_name='news_articles')
    op.drop_index('idx_news_articles_asset_id', table_name='news_articles')
    op.drop_column('news_articles', 'sentiment_label')
    op.drop_column('news_articles', 'sentiment_score')
    op.drop_column('news_articles', 'asset_symbol')
    op.drop_column('news_articles', 'asset_id')
    # ### end Alembic commands ###
